repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: nox -rs autoflake
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: nox -rs isort
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: black
        name: black
        entry: nox -rs black
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: nox -rs mypy
        language: system
        pass_filenames: false
