site_name: Koila
nav:
  - "README.md"
  - "LICENSE.md"
  - "CODE_OF_CONDUCT.md"
theme:
  name: material
  font:
    text: Open Sans
    code: Fira Code
  icon:
    repo: material/github
edit_uri: ""
repo_name: rentruewang/koila
repo_url: https://github.com/rentruewang/koila
plugins:
  - git-revision-date:
      enabled_if_env: CI
  - git-revision-date-localized:
      type: date
