# Copyright (c) AIoWay Authors - All Rights Reserved

"Terms allows attributes to support the same operations."

import typing
from typing import Protocol, Self

__all__ = ["Term"]


class Term[T](Protocol):
    """
    The terms API is equivalent to a registry; defining the operations that we must support.
    """

    def __invert__(self) -> Self: ...

    def __neg__(self) -> Self: ...

    def __add__(self, other: Self) -> Self: ...

    def __sub__(self, other: Self) -> Self: ...

    def __mul__(self, other: Self) -> Self: ...

    def __truediv__(self, other: Self) -> Self: ...

    def __floordiv__(self, other: Self) -> Self: ...

    def __mod__(self, other: Self) -> Self: ...

    def __pow__(self, other: Self) -> Self: ...

    @typing.no_type_check
    def __eq__(self, other: Self) -> Self: ...

    @typing.no_type_check
    def __ne__(self, other: Self) -> Self: ...

    def __ge__(self, other: Self) -> Self: ...

    def __gt__(self, other: Self) -> Self: ...

    def __le__(self, other: Self) -> Self: ...

    def __lt__(self, other: Self) -> Self: ...

    def unpack(self) -> T: ...

    @classmethod
    def make(cls, data: T) -> Self: ...
