title: Koila
author: RenChu Wang
copyright: RenChu Wang, 2024
logo: assets/koila.png

exclude_patterns: [_build]
only_build_toc_files: true

repository:
  url: https://github.com/rentruewang/koila

html:
  use_repository_button: true

execute:
  execute_notebooks: force
