# Copyright (c) AIoWay Authors - All Rights Reserved

import dataclasses as dcls
import functools
import logging
from abc import ABC
from collections.abc import Callable, Generator
from typing import Any, Self

from aioway import registries
from aioway.blocks import Block
from aioway.errors import AiowayError
from aioway.nodes import Node

from .ops import Op
from .pollers import Poller

__all__ = ["Exec", "Execution"]

LOGGER = logging.getLogger(__name__)


@dcls.dataclass
class Exec(Node["Exec"]):
    """
    ``Exec`` is the graph / symbolic representation of an execution.

    An execution itself does not store state,
    but rather launches an iterator / cursor to iterate over the data.
    This design allows users to write genertors (``__iter__`` funciton),
    rather than iterators (``__next__`` function) with state management.
    """

    poller: Poller
    """
    The ``Poller`` that determines the iteration strategy,
    as well as the children of the current ``Execution``.
    """

    op_type: type[Op]
    """
    The type of ``Op`` which is a pure function,
    representing the function being applied to the data being generated by poller.
    """

    op_opts: dict[str, Any]
    """
    The options / kwargs for ``Op``.
    """

    def __iter__(self) -> Generator[Block, Any, None]:
        for batch in self.poller:
            yield self.op(batch)

    @functools.cached_property
    def op(self) -> Op:
        return self.op_type(**self.op_opts)

    @classmethod
    def builder(cls, poller: type[Poller], op: type[Op]) -> Callable[..., Self]:
        """
        The builder method for ``Exec``s.

        Args:
            poller: The type of ``Poller`` to use. Must be a subclass of ``Poller``.
            op: The type of ``Op`` to use. Must be a subclass of ``Op``.

        Returns:
            A function that takes in the input ``Exec``s as ``*args``,
            and options for ``Op``s as ``**kwargs``.
        """

        if not issubclass(poller, Poller):
            raise ExecBuilderError(
                f"Got poller type {poller} should be a subclass of `Poller` instead."
            )

        if not issubclass(op, Op):
            raise ExecBuilderError(
                f"Got op type {op} should be a subclass of `Op` instead."
            )

        def func(*execs, **options):
            for exe in execs:
                if not isinstance(exe, Exec):
                    raise ExecBuilderError(
                        f"Children must be instances of `Exec`s. Got {type(exe)=}."
                    )

            return cls(poller=poller(*execs), op_type=op, op_opts=options)

        return func


@dcls.dataclass
class Execution(Node["Execution"], ABC):
    """
    ``Execution`` represents an execution (an iterator or cursor).

    Upon launch (via ``iter``), it would kick off a stream of heterogenious data.

    It can be thought of as an ``Iterator`` of ``Block``s,
    where computation happens lazily, imperatively, and the result is yielded.
    """

    def __init_subclass__(cls, *, key: str = ""):
        # Ensure that concrete subclasses can be instantiated from a factory.
        cls.__register_factory_with_key(cls, key=key)

    def __hash__(self) -> int:
        """
        The unique identifier of each node, representing computation.

        This means that ``__hash__`` would be the same for shared computation.

        For now, it is the ``id`` of the object itself,
        and the object itself is the unique identifier of the computation.
        However, in the future, we might want to use a more sophisticated way to identify computation
        for distributed execution and caching.
        """

        return id(self)

    def __iter__(self):
        return self

    def __next__(self):
        raise NotImplementedError

    # @property
    # def children(self):
    #     return self.poller.children

    __register_factory_with_key = registries.init_subclass(lambda: Execution)
    """
    Register subclasses with the given key into the factory.
    """


class ExecRegisterError(AiowayError, KeyError): ...


class ExecBuilderError(AiowayError, TypeError): ...
